sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y thrift-compiler

#install: /bin/true

script: gradle crypto:install token:install warp10:pack


notifications:
  email: false
